"""创业板指信号阈值。"""

from config.env import _env_bool, _env_float, _env_int
from config.price_position import (
    BUY_NEAR_YEAR_LOW_RANGE_PCT,
    BUY_TREND_MA_DAYS,
    BUY_TREND_SLOPE_LOOKBACK_DAYS,
)

# --- 创业板指（399006）---
# 买入：PEG(近5年增速) + 价格位置 + MA 趋势
CYB_EXPECTED_GROWTH = _env_float("CYB_EXPECTED_GROWTH", 0.3906)
# 兜底固定增速；启用自动时优先用面板滚动 5 年盈利 CAGR（close/PE）
CYB_HISTORICAL_GROWTH = _env_float("CYB_HISTORICAL_GROWTH", 0.1663)
CYB_HISTORICAL_GROWTH_AUTO = _env_bool("CYB_HISTORICAL_GROWTH_AUTO", True)
CYB_HISTORICAL_GROWTH_YEARS = _env_int("CYB_HISTORICAL_GROWTH_YEARS", 5)
CYB_HISTORICAL_GROWTH_MIN_DAYS = _env_int("CYB_HISTORICAL_GROWTH_MIN_DAYS", 756)
# 自动 CAGR 下限：默认等于历史兜底，避免自动化把 PEG 收得比原策略更严；
# 若希望按真实低增速收紧，可将 floor 调低（如 0.10）
CYB_HISTORICAL_GROWTH_FLOOR = _env_float("CYB_HISTORICAL_GROWTH_FLOOR", 0.1663)
CYB_ROE_AVG = _env_float("CYB_ROE_AVG", 0.1229)
# 创业板指：2016-2025 夏普偏低(0.41)且回撤大，收紧买入
CYB_BUY_PEG_HIST_MAX = _env_float("CYB_BUY_PEG_HIST_MAX", 2.2)
CYB_PERCENTILE_WINDOW = _env_int("CYB_PERCENTILE_WINDOW", 2520)
CYB_DIV_PERCENTILE_WINDOW = _env_int("CYB_DIV_PERCENTILE_WINDOW", 1260)
CYB_PERCENTILE_MIN_DAYS = _env_int("CYB_PERCENTILE_MIN_DAYS", 120)
CYB_BUY_MAX_ABOVE_LOW_PCT = _env_float("CYB_BUY_MAX_ABOVE_LOW_PCT", 0.06)
CYB_BUY_LOW_LOOKBACK_DAYS = _env_int("CYB_BUY_LOW_LOOKBACK_DAYS", 90)
CYB_BUY_HIGH_LOOKBACK_DAYS = _env_int("CYB_BUY_HIGH_LOOKBACK_DAYS", 252)
CYB_BUY_MID_RANGE_POSITION_PCT = _env_float(
    "CYB_BUY_MID_RANGE_POSITION_PCT", 0.45
)
CYB_BUY_MID_RANGE_MAX_ABOVE_LOW_PCT = _env_float(
    "CYB_BUY_MID_RANGE_MAX_ABOVE_LOW_PCT", 0.06
)
CYB_BUY_TREND_MA_DAYS = _env_int("CYB_BUY_TREND_MA_DAYS", BUY_TREND_MA_DAYS)
CYB_BUY_TREND_SLOPE_LOOKBACK_DAYS = _env_int(
    "CYB_BUY_TREND_SLOPE_LOOKBACK_DAYS", BUY_TREND_SLOPE_LOOKBACK_DAYS
)
CYB_BUY_TREND_MIN_MA_SLOPE_PCT = _env_float(
    "CYB_BUY_TREND_MIN_MA_SLOPE_PCT", -0.015
)
CYB_BUY_TREND_DOWNTREND_MAX_RANGE_PCT = _env_float(
    "CYB_BUY_TREND_DOWNTREND_MAX_RANGE_PCT", 0.08
)
CYB_BUY_NEAR_YEAR_LOW_RANGE_PCT = _env_float(
    "CYB_BUY_NEAR_YEAR_LOW_RANGE_PCT", BUY_NEAR_YEAR_LOW_RANGE_PCT
)

