"""价格位置与趋势过滤（全局默认）。"""

from config.env import _env_float, _env_int, _env_int_any, _env_float_any, _env_str

# 滚动区间位置（默认近 252 交易日 ≈ 1 年）：0=窗口内最低、1=窗口内最高
BUY_RANGE_LOOKBACK_DAYS = _env_int("BUY_RANGE_LOOKBACK_DAYS", 252)
BUY_MAX_YEAR_RANGE_PCT = _env_float("BUY_MAX_YEAR_RANGE_PCT", 0.58)
BUY_NEAR_YEAR_LOW_RANGE_PCT = _env_float("BUY_NEAR_YEAR_LOW_RANGE_PCT", 0.20)
BUY_NEAR_YEAR_LOW_SPREAD_RELAX = _env_float("BUY_NEAR_YEAR_LOW_SPREAD_RELAX", 10)
BUY_NEAR_YEAR_LOW_PE_RELAX = _env_float("BUY_NEAR_YEAR_LOW_PE_RELAX", 12)
BUY_NEAR_YEAR_LOW_ABOVE_LOW_RELAX = _env_float("BUY_NEAR_YEAR_LOW_ABOVE_LOW_RELAX", 0.04)
BUY_NEAR_YEAR_LOW_DRAWDOWN_WAIVE_PCT = _env_float(
    "BUY_NEAR_YEAR_LOW_DRAWDOWN_WAIVE_PCT", 0.12
)
BUY_MID_RANGE_POSITION_PCT = _env_float("BUY_MID_RANGE_POSITION_PCT", 0.45)
BUY_MID_RANGE_MAX_ABOVE_LOW_PCT = _env_float("BUY_MID_RANGE_MAX_ABOVE_LOW_PCT", 0.06)
# 均线趋势过滤：MA200 斜率（默认 60 日变化率）
BUY_TREND_MA_DAYS = _env_int("BUY_TREND_MA_DAYS", 200)
BUY_TREND_SLOPE_LOOKBACK_DAYS = _env_int("BUY_TREND_SLOPE_LOOKBACK_DAYS", 60)
BUY_TREND_MIN_MA_SLOPE_PCT = _env_float("BUY_TREND_MIN_MA_SLOPE_PCT", -0.02)
BUY_TREND_DOWNTREND_MAX_RANGE_PCT = _env_float(
    "BUY_TREND_DOWNTREND_MAX_RANGE_PCT", 0.10
)
