"""美股指数信号阈值。"""

from config.env import _env_float, _env_int, _env_str
from config.price_position import (
    BUY_NEAR_YEAR_LOW_PE_RELAX,
    BUY_NEAR_YEAR_LOW_RANGE_PCT,
    BUY_TREND_MA_DAYS,
    BUY_TREND_SLOPE_LOOKBACK_DAYS,
)

# --- 纳斯达克 100（NDX）---
# 买入：Forward PE 分位 + 10Y 利率分位 + 年区间位置 + MA 趋势
NDX_FORWARD_PE_URL = _env_str(
    "NDX_FORWARD_PE_URL",
    "https://historyofmarket.com/api/ndx/forward-pe.json",
)
NDX_DIVIDEND_PROXY_SYMBOL = _env_str("NDX_DIVIDEND_PROXY_SYMBOL", "QQQ")
NDX_EXPECTED_GROWTH = _env_float("NDX_EXPECTED_GROWTH", 0.0) or None
NDX_FALLBACK_EXPECTED_GROWTH = _env_float("NDX_FALLBACK_EXPECTED_GROWTH", 0.19)
NDX_BUY_FORWARD_PE_PERCENTILE_MAX = _env_float(
    "NDX_BUY_FORWARD_PE_PERCENTILE_MAX", 87
)
NDX_BUY_RATE_PERCENTILE_MAX = _env_float("NDX_BUY_RATE_PERCENTILE_MAX", 99)
NDX_BUY_RATE_SLOPE_LOOKBACK_DAYS = _env_int("NDX_BUY_RATE_SLOPE_LOOKBACK_DAYS", 21)
NDX_BUY_RATE_MAX_SLOPE = _env_float("NDX_BUY_RATE_MAX_SLOPE", 0.004)
NDX_HISTORY_YEARS = _env_int("NDX_HISTORY_YEARS", 10)
NDX_PERCENTILE_WINDOW = _env_int("NDX_PERCENTILE_WINDOW", 120)
NDX_PERCENTILE_MIN_DAYS = _env_int("NDX_PERCENTILE_MIN_DAYS", 24)
NDX_DAILY_PERCENTILE_WINDOW = _env_int("NDX_DAILY_PERCENTILE_WINDOW", 2520)
NDX_DAILY_PERCENTILE_MIN_DAYS = _env_int("NDX_DAILY_PERCENTILE_MIN_DAYS", 252)
NDX_FRED_NETWORK_TIMEOUT = _env_int("NDX_FRED_NETWORK_TIMEOUT", 10)
NDX_BUY_MAX_ABOVE_LOW_PCT = _env_float("NDX_BUY_MAX_ABOVE_LOW_PCT", 0.38)
NDX_BUY_LOW_LOOKBACK_DAYS = _env_int("NDX_BUY_LOW_LOOKBACK_DAYS", 90)
NDX_BUY_HIGH_LOOKBACK_DAYS = _env_int("NDX_BUY_HIGH_LOOKBACK_DAYS", 252)
NDX_BUY_MIN_DRAWDOWN_FROM_HIGH_PCT = _env_float(
    "NDX_BUY_MIN_DRAWDOWN_FROM_HIGH_PCT", 0.0
)
NDX_BUY_MAX_YEAR_RANGE_PCT = _env_float("NDX_BUY_MAX_YEAR_RANGE_PCT", 0.68)
NDX_BUY_MID_RANGE_POSITION_PCT = _env_float(
    "NDX_BUY_MID_RANGE_POSITION_PCT", 0.45
)
NDX_BUY_MID_RANGE_MAX_ABOVE_LOW_PCT = _env_float(
    "NDX_BUY_MID_RANGE_MAX_ABOVE_LOW_PCT", 0.10
)
NDX_BUY_TREND_MA_DAYS = _env_int("NDX_BUY_TREND_MA_DAYS", BUY_TREND_MA_DAYS)
NDX_BUY_TREND_SLOPE_LOOKBACK_DAYS = _env_int(
    "NDX_BUY_TREND_SLOPE_LOOKBACK_DAYS", BUY_TREND_SLOPE_LOOKBACK_DAYS
)
NDX_BUY_TREND_MIN_MA_SLOPE_PCT = _env_float(
    "NDX_BUY_TREND_MIN_MA_SLOPE_PCT", -0.02
)
NDX_BUY_TREND_DOWNTREND_MAX_RANGE_PCT = _env_float(
    "NDX_BUY_TREND_DOWNTREND_MAX_RANGE_PCT", 0.30
)
NDX_BUY_NEAR_YEAR_LOW_RANGE_PCT = _env_float(
    "NDX_BUY_NEAR_YEAR_LOW_RANGE_PCT", BUY_NEAR_YEAR_LOW_RANGE_PCT
)
NDX_BUY_NEAR_YEAR_LOW_PE_RELAX = _env_float(
    "NDX_BUY_NEAR_YEAR_LOW_PE_RELAX", BUY_NEAR_YEAR_LOW_PE_RELAX
)
NDX_BUY_NEAR_YEAR_LOW_RATE_RELAX = _env_float(
    "NDX_BUY_NEAR_YEAR_LOW_RATE_RELAX", 12
)

# --- 标普 500（SPX，逻辑参考纳斯达克 100）---
SPX_FORWARD_PE_URL = _env_str(
    "SPX_FORWARD_PE_URL",
    "https://historyofmarket.com/api/sp500/forward-pe.json",
)
SPX_DIVIDEND_PROXY_SYMBOL = _env_str("SPX_DIVIDEND_PROXY_SYMBOL", "SPY")
SPX_EXPECTED_GROWTH = _env_float("SPX_EXPECTED_GROWTH", 0.0) or None
SPX_FALLBACK_EXPECTED_GROWTH = _env_float("SPX_FALLBACK_EXPECTED_GROWTH", 0.10)
SPX_BUY_FORWARD_PE_PERCENTILE_MAX = _env_float(
    "SPX_BUY_FORWARD_PE_PERCENTILE_MAX", 87
)
SPX_BUY_RATE_PERCENTILE_MAX = _env_float("SPX_BUY_RATE_PERCENTILE_MAX", 99)
SPX_BUY_RATE_SLOPE_LOOKBACK_DAYS = _env_int("SPX_BUY_RATE_SLOPE_LOOKBACK_DAYS", 21)
SPX_BUY_RATE_MAX_SLOPE = _env_float("SPX_BUY_RATE_MAX_SLOPE", 0.004)
SPX_HISTORY_YEARS = _env_int("SPX_HISTORY_YEARS", 10)
SPX_PERCENTILE_WINDOW = _env_int("SPX_PERCENTILE_WINDOW", 120)
SPX_PERCENTILE_MIN_DAYS = _env_int("SPX_PERCENTILE_MIN_DAYS", 24)
SPX_DAILY_PERCENTILE_WINDOW = _env_int("SPX_DAILY_PERCENTILE_WINDOW", 2520)
SPX_DAILY_PERCENTILE_MIN_DAYS = _env_int("SPX_DAILY_PERCENTILE_MIN_DAYS", 252)
SPX_FRED_NETWORK_TIMEOUT = _env_int("SPX_FRED_NETWORK_TIMEOUT", 10)
SPX_BUY_MAX_ABOVE_LOW_PCT = _env_float("SPX_BUY_MAX_ABOVE_LOW_PCT", 0.35)
SPX_BUY_LOW_LOOKBACK_DAYS = _env_int("SPX_BUY_LOW_LOOKBACK_DAYS", 90)
SPX_BUY_HIGH_LOOKBACK_DAYS = _env_int("SPX_BUY_HIGH_LOOKBACK_DAYS", 252)
SPX_BUY_MIN_DRAWDOWN_FROM_HIGH_PCT = _env_float(
    "SPX_BUY_MIN_DRAWDOWN_FROM_HIGH_PCT", 0.0
)
SPX_BUY_MAX_YEAR_RANGE_PCT = _env_float("SPX_BUY_MAX_YEAR_RANGE_PCT", 0.68)
SPX_BUY_MID_RANGE_POSITION_PCT = _env_float(
    "SPX_BUY_MID_RANGE_POSITION_PCT", 0.45
)
SPX_BUY_MID_RANGE_MAX_ABOVE_LOW_PCT = _env_float(
    "SPX_BUY_MID_RANGE_MAX_ABOVE_LOW_PCT", 0.10
)
SPX_BUY_TREND_MA_DAYS = _env_int("SPX_BUY_TREND_MA_DAYS", BUY_TREND_MA_DAYS)
SPX_BUY_TREND_SLOPE_LOOKBACK_DAYS = _env_int(
    "SPX_BUY_TREND_SLOPE_LOOKBACK_DAYS", BUY_TREND_SLOPE_LOOKBACK_DAYS
)
SPX_BUY_TREND_MIN_MA_SLOPE_PCT = _env_float(
    "SPX_BUY_TREND_MIN_MA_SLOPE_PCT", -0.02
)
SPX_BUY_TREND_DOWNTREND_MAX_RANGE_PCT = _env_float(
    "SPX_BUY_TREND_DOWNTREND_MAX_RANGE_PCT", 0.30
)
SPX_BUY_NEAR_YEAR_LOW_RANGE_PCT = _env_float(
    "SPX_BUY_NEAR_YEAR_LOW_RANGE_PCT", BUY_NEAR_YEAR_LOW_RANGE_PCT
)
SPX_BUY_NEAR_YEAR_LOW_PE_RELAX = _env_float(
    "SPX_BUY_NEAR_YEAR_LOW_PE_RELAX", BUY_NEAR_YEAR_LOW_PE_RELAX
)
SPX_BUY_NEAR_YEAR_LOW_RATE_RELAX = _env_float(
    "SPX_BUY_NEAR_YEAR_LOW_RATE_RELAX", 12
)

